CONFIG = {
    "engine": {
        "target_fps": 30,
        "input_timeout": 0.05,
        "math_center_divisor": 2,
        "plugins": [
            "passbox",
            "advanced_greeter",
            "dim_forcer",
            "starting_song",
            "wallpaper",
        ],
    },
    "theme": {
        "bg_color": (15, 15, 20),
        "box_bg": (30, 30, 40),
        "text_main": (220, 220, 220),
        "text_accent": (255, 100, 100),
        "text_error": (255, 80, 80),
        "text_success": (80, 255, 80),
    },
    "layout": {
        "z_background": 0,
        "z_ui_base": 4,
        "z_ui_elements": 5,
        "z_overlay": 10,
        "box_width": 44,
        "box_height": 10,
        "box_x": "center",
        "box_y": "center",
        "title_y": "box_bg.top + 2",
        "title_x": "box_bg.centerx",
        "padx": "box_bg.left+3",
        "user_y": "c:layout:title_y+2",
        "user_x": "c:layout:padx",
        "pass_y": "c:layout:user_y+2",
        "pass_x": "c:layout:padx",
        "msg_y": "c:layout:pass_y+2",
        "msg_x": "c:layout:padx-1",
    },
    "anchors": {"box_bg": "center", "title": "center"},
    "text": {
        "title": " Hyprland ",
        "user_active": "> user: ",
        "user_idle": "  user: ",
        "pass_active": "> pass: ",
        "pass_idle": "  pass: ",
        "mask_char": "*",
        "msg_authenticating": "Authenticating...",
        "msg_success": "Login successful. Starting...",
        "msg_fail": "Authentication failed.",
    },
    "system": {
        "default_session_cmd": [
            "bash",
            "-l",
            "-c",
            "dbus-run-session Hyprland > /tmp/hyprland.log 2>&1",
        ],
        "empty_string": "",
    },
}
