[project]
name = "log"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Plazio108", email = "plazio108@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "gleaf",
    "lz4>=4.4.5",
    "numpy>=2.5.2",
    "oakey",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
]

[project.scripts]
log = "log:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
gleaf = { git = "https://github.com/Plazio108/gleaf.git" }
oakey = { git = "https://github.com/Plazio108/oakey.git" }
